Reactivate the integration tests for remote file access (GCS, S3)
- 2 fake servers (fakes3 and fake-gcs-server) are used locally instead of a real S3 and GCS servers.
- The fake servers are pre-provisioned with sample files to be ready before the tests run
- During the construction of the khiopsdev docker image we need to install the s3/gcs drivers required by khiops

diff --git a/packaging/docker/khiopspydev/Dockerfile.ubuntu b/packaging/docker/khiopspydev/Dockerfile.ubuntu
--- a/packaging/docker/khiopspydev/Dockerfile.ubuntu
+++ b/packaging/docker/khiopspydev/Dockerfile.ubuntu
@@ -10,15 +10,14 @@ ARG KHIOPS_REVISION
 RUN true \
   # Install git (for khiops-python version calculation) and pip \
   && apt-get -y update \
-  && apt-get -y --no-install-recommends install git python3-pip zip pandoc wget \
+  && apt-get -y --no-install-recommends install git python3-pip zip pandoc wget ruby-dev \
   # Get Linux distribution codename \
   && if [ -f /etc/os-release ]; then . /etc/os-release; fi \
   # Obtain the Khiops native package \
   && KHIOPS_PKG_FILE=$KHIOPS_REVISION/khiops-core-openmpi_$KHIOPS_REVISION-1-$VERSION_CODENAME.amd64.deb \
   && wget -O KHIOPS_CORE.deb "https://github.com/KhiopsML/khiops/releases/download/${KHIOPS_PKG_FILE}" \
-  # Install the Khiops native package \
-  && dpkg -i --force-all KHIOPS_CORE.deb \
-  && apt-get -f -y install \
+  # Install the Khiops native package : do not break immediately if dpkg fails because apt will install the missing dependencies \
+  && (dpkg -i --force-all KHIOPS_CORE.deb || true) && apt-get -f -y install \
   && rm -f KHIOPS_CORE.deb \
   # Set python to python3 \
   && update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
@@ -48,9 +47,37 @@ done'
 
 RUN mkdir -p /scripts
 COPY ./run_service.sh /scripts/run_service.sh
-RUN chmod +x /scripts/run_service.sh && \
+COPY ./run_fake_remote_file_servers.sh /scripts/run_fake_remote_file_servers.sh
+RUN chmod +x /scripts/*.sh && \
   useradd -rm -d /home/ubuntu -s /bin/bash -g root -u 1000 ubuntu
 
+# new gcs & s3 drivers (written in C++)
+ARG KHIOPS_GCS_DRIVER_VERSION
+ARG KHIOPS_S3_DRIVER_VERSION
+RUN true \
+    && wget -O khiops-gcs.deb https://github.com/KhiopsML/khiopsdriver-gcs/releases/download/${KHIOPS_GCS_DRIVER_VERSION}/khiops-gcs_${KHIOPS_GCS_DRIVER_VERSION}.deb \
+    && wget -O khiops-s3.deb https://github.com/KhiopsML/khiopsdriver-s3/releases/download/${KHIOPS_S3_DRIVER_VERSION}/khiops-s3_${KHIOPS_S3_DRIVER_VERSION}.deb \
+    && (dpkg -i --force-all khiops-gcs.deb khiops-s3.deb || true) && apt-get -f -y install \
+    && rm -f khiops-gcs.deb khiops-s3.deb \
+    && true
+
 FROM ghcr.io/khiopsml/khiops-server:${SERVER_REVISION} AS server
+FROM fsouza/fake-gcs-server:1.49 AS gcs-server
+
 FROM khiopsdev AS base
 COPY --from=server /service /usr/bin/service
+
+# GCS fake file server (only in the ubuntu container)
+COPY --from=gcs-server /bin/fake-gcs-server /bin/fake-gcs-server
+EXPOSE 4443
+
+# S3 fake file server (only in the ubuntu container)
+# Do not use the latest fakes3 version because starting from 1.3.1 a licence is required
+RUN gem install fakes3:0.2.5 sorted_set
+# Avoid resolving a fake s3-bucket.localhost hostname
+# Alternate builders (buildx via moby buildkit) mount /etc/hosts read-only, the following command will fail
+# echo "127.0.0.1 s3-bucket.localhost" >> /etc/hosts
+# You will have to add the `add-hosts` input instead (https://github.com/docker/build-push-action/#inputs)
+
+EXPOSE 4569
+
