Drop versioneer and hard-code the version, as for the Khiops binaries
Notes:
- the version is hard-coded in the khiops/__init__.py file and not in
  pyproject.toml, because pyproject.toml is not accessible at runtime
  for an installed package
- conda-build does not support pyproject.toml-style dynamic versions,
  hence the version has to be hard-coded in conda/meta.yaml as well
- when moving to conda-forge, the version would have to be hard-coded
  anyway
- the khiops/__init__.py vs conda/meta.yaml version coherence is checked
  in the conda package building and testing workflow.

diff --git a/.github/workflows/conda.yml b/.github/workflows/conda.yml
--- a/.github/workflows/conda.yml
+++ b/.github/workflows/conda.yml
@@ -111,6 +111,21 @@ jobs:
           fi
           conda install ${RC_LABEL}khiops-core=$KHIOPS_CORE_VERSION
           conda install --channel ./khiops-conda/ khiops
+      - name: Install JQ test dependency (Linux / MacOS)
+        if: runner.os != 'Windows'
+        run: conda install jq
+      - name: Test Conda / Python Package Version Coherence
+        run: |
+          PACKAGE_VERSION=$(python -c "import khiops; print(khiops.__version__)")
+          CONDA_VERSION=$(conda list ^khiops$ --json | jq ".[].version")
+
+          # Fail if CONDA_VERSION is not identical to $PACKAGE_VERSION
+          echo $CONDA_VERSION | grep -wq $PACKAGE_VERSION
+          if [[ $? -ne 0 ]]
+          then
+            echo "::error::Conda package version $CONDA_VERSION does not match Python package version $PYTHON_VERSION"
+            false
+          fi
       - name: Test Khiops Installation Status
         run: kh-status
       - name: Test Khiops Installation Status (Conda-Based Environments)
